# .github/workflows/lint.yml
name: Lint and Format Check

# Run on pushes to the main branch and on pull requests targeting main
on:
  push:
    branches: [ "main" ] # Adjust branch names if needed (e.g., "master")
  pull_request:

# Allow only one concurrent run for the same workflow, branch/PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ruff_check:
    name: Run Ruff Linter and Formatter
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
    - name: Check out repository
      uses: actions/checkout@v4 # Use the latest checkout action

    - name: Set up Python
      uses: actions/setup-python@v5 # Use the latest setup-python action
      with:
        python-version: '3.10' # Use the Python version your project targets
        cache: 'pip' # Cache pip dependencies

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff 

    - name: Run Ruff Linter Check
      run: ruff check --output-format=github .

    - name: Run Ruff Formatter Check
      run: ruff format --check .